# Pre-commit hooks for GitHub Actions Quality Automation
repos:
  # JavaScript/TypeScript/React
  - repo: local
    hooks:
      - id: eslint-check
        name: ESLint Check
        entry: bash -c 'if [[ -f "package.json" ]]; then npm run lint; fi'
        language: system
        files: '\.(js|jsx|ts|tsx)$'
        pass_filenames: false
        
      - id: prettier-check
        name: Prettier Check
        entry: bash -c 'if [[ -f "package.json" ]] && command -v npx &> /dev/null; then npx prettier --check .; fi'
        language: system
        files: '\.(js|jsx|ts|tsx|json|css|scss|md)$'
        pass_filenames: false

  # Python
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # PHP
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: PHP CS Fixer
        entry: bash -c 'if [[ -f ".php-cs-fixer.php" ]] && command -v php-cs-fixer &> /dev/null; then php-cs-fixer fix --dry-run --diff; fi'
        language: system
        files: '\.php$'
        pass_filenames: false
        
      - id: phpstan
        name: PHPStan
        entry: bash -c 'if [[ -f "phpstan.neon" ]] && command -v phpstan &> /dev/null; then phpstan analyse; fi'
        language: system
        files: '\.php$'
        pass_filenames: false

  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: mixed-line-ending
        args: ['--fix=lf']